### ISSUE TITLE
Refactoring sparql_server configuration

### ISSUE THREAD

**Issue by xgaia** [souslesens/souslesensVocables#302]
- Bouger la config du sparql endoint
```
sparql_server:
  url:
  username: 
  password:
```
- Pas d'appel au serveur sparql coté client
- Ne pas remonter la config coté client
- Bouger tous les appels SPARQL dans la route /sparql existante.

**Comment by xgaia** [comment]
garder `default_sparql_server`

```yaml
default_sparql_server:
  url: xxx
  username: xxx
  password: xxx
```
